apiVersion: constraints.gatekeeper.sh/v1beta1
kind: IngressRequiredLabels
metadata:
  name: ingress-must-have-owner
spec:
  match:
    kinds:
      - apiGroups: ["extensions", "networking.k8s.io"]
        kinds: ["Ingress"]
  parameters:
    message: "All Ingress must have an `owner` label that points to your company username"
    labels:
      - key: owner
        allowedRegex: "kris"
