apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: allowedprojectpvcforsc
spec:
  crd:
    spec:
      names:
        kind: AllowedProjectPvcforSc
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            projects:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package allowedprojectpvcforsc
        violation[{"msg": msg}] {
          pvcnamespace := input.review.object.metadata.namespace
          not ns_in_project(pvcnamespace)
          input.review.object.spec.storageClassName == "longhorn"
          msg := sprintf("storage pvc <%v> is not allowed in this project, allowed projects are %v", [input.review.object.metadata.name, input.parameters.projects])
        }

        ns_in_project(pvcnamespace) = true {
          nsobject := data.inventory.cluster[_][_][name]
          nsobject.metadata.name == pvcnamespace
          pvcproject := nsobject.metadata.labels["field.cattle.io/projectId"]
          pvcproject == input.parameters.projects[_]
        }


