apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: allowedprojectpvcforsc
spec:
  crd:
    spec:
      names:
        kind: AllowedProjectPvcforSc
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            projects:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package allowedprojectpvcforsc
        violation[{"msg": msg}] {
          pvcnamespace := input.review.object.metadata.namespace
          not ns_in_project
          input.review.object.spec.storageClassName == "longhorn"
          msg := sprintf("storage pvc <%v> is not allowed in this project, allowed projects are %v", [input.review.object.metadata.name, input.parameters.projects])
        }

        ns_in_project = true {
          key := "field.cattle.io/projectId"
          pvcproject := ns_obj_pvc[objns].metadata.labels[key]
          pvcproject == input.parameters.projects[_]
        }
        ns_obj_pvc[objns] {
          objns := data.inventory.cluster[_][_]["Namespace"][name]
          objns.metadata.name == input.review.object.metadata.namespace
        }
